### ISSUE TITLE
Columns overlap but no suffix specified

### ISSUE THREAD

**Issue by Rensvandeschoot** [rohitgarud/asreview-notes-export#2]
This is a great contribution to the ASReview universe and highly wanted by users, see the discussion at https://github.com/asreview/asreview/discussions/1220.

When I ran the extension I ran into an issue. To reproduce:

I initiated a project in ASReview, added one note, and exported the project: [example-ptsd.zip](https://github.com/rohitgarud/asreview-notes-export/files/10456243/example-ptsd.zip) (The file I used is attached (it needs to be unzipped first).)

When running 

```
asreview notes_export example-ptsd.asreview
```

I obtained the following warning:

```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\asreview.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\asreview\__main__.py", line 78, in main
    entry.load()().execute(sys.argv[2:])
  File "C:\Python310\lib\site-packages\asreviewcontrib\notes_export\entrypoint.py", line 42, in execute
    export_notes(
  File "C:\Python310\lib\site-packages\asreviewcontrib\notes_export\notes_export.py", line 39, in export_notes
    dataset_with_results = dataset.df.join(df.set_index('record_id')[['labeling_order','label','notes']])
  File "C:\Python310\lib\site-packages\pandas\core\frame.py", line 9254, in join
    return self._join_compat(
  File "C:\Python310\lib\site-packages\pandas\core\frame.py", line 9285, in _join_compat
    return merge(
  File "C:\Python310\lib\site-packages\pandas\core\reshape\merge.py", line 122, in merge
    return op.get_result()
  File "C:\Python310\lib\site-packages\pandas\core\reshape\merge.py", line 718, in get_result
    llabels, rlabels = _items_overlap_with_suffix(
  File "C:\Python310\lib\site-packages\pandas\core\reshape\merge.py", line 2313, in _items_overlap_with_suffix
    raise ValueError(f"columns overlap but no suffix specified: {to_rename}")
```

**Comment by rohitgarud** [comment]
Thank you. I will look into it and get back as soon as possible.

**Comment by elisebvd** [comment]
I got a similar error. I think it has something to do with the fact that my original file with all records already contains a column 'notes'. So the new column with the notes created during screening in ASReview need a suffix to create unique columnnames.

**Comment by rohitgarud** [comment]
Yes @elisebvd . You are right. That is the reason behind the error. I have resolved that bug in my local repo. Will upload the updated version to PyPI soon and will notify you here.

**Comment by rohitgarud** [comment]
@Rensvandeschoot , @elisebvd I have updated the pypi version. Please check and let me know if it is working as expected.

**Comment by Rensvandeschoot** [comment]
Perfect! I obtained the file with an additional column `exported_notes`

**Comment by elisebvd** [comment]
Yes, it worked for me as well, great!

**Comment by rohitgarud** [comment]
Thank you for your response, @Rensvandeschoot @elisebvd. Please let me know if any other functionality can be added to this extension. Also, is this extension worth adding to the list of community-maintained extensions in Asreview discussion #1140. Thank you.

**Comment by Rensvandeschoot** [comment]
great!! and I will add your extension to our documentation!

**Comment by rohitgarud** [comment]
Thank you very much. I am working on another extension, I will soon upload it on pipy and ping you for your expert review. Thank you for your support and guidance @Rensvandeschoot
